environment:
  image: Visual Studio 2019

install:

  #- "%CMD_IN_ENV% set"

  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

  - "git clone https://github.com/Microsoft/vcpkg.git"
  - "cd vcpkg"
  - "bootstrap-vcpkg.bat"
  - "vcpkg integrate install"



build_script:
  - "vcpkg install curl[brotli,c-ares,core,http2,mbedtls,openssl,ssh,ssl,sspi,winssl]:x86-windows"