# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x86' script'
   inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64' script'
   inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x86' script'
   inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64' script'
